name: CI

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Test book
        run: mdbook test
      - name: Build book
        run: mdbook build
